server:
  port : 8081
feign:
  client:
    config:
      products:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false
        ribbon:
          listOfServers: localhost:8082
  hystrix:
    enabled: false
products:
  ribbon:
    listOfServers: localhost:8082
ribbon:
  eureka:
    enabled: false